version: '2'
services:
    playas-app:
        image: playas
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://playas-mysql:3306/playas?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    playas-mysql:
        extends:
            file: mysql.yml
            service: playas-mysql
